"""Build a comprehensive multi-metric markdown table covering ALL trajectories.

Reports per-pair × per-condition: AR@100, AR@500, AR@1000, MedAE, MaxAE,
MeanAE, LR@500_K5, Robustness (MedAE<2s). No metric hidden.

Conditions covered:
  - Dixon+CQT baseline (paper's strongest pure baseline)
  - Hybrid v1 (slow_beats≥50 trigger)
  - Hybrid v2 (SLOW_TERMS-only trigger + safety-net)
  - Pass-1 rule plan (Arzt+STFT+quant_plan)
  - Pass-2 confidence-gated rehearsal
  - Best-of-3 selection (oracle)

Output: RESULTS_FULL_METRICS.md
"""
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).parent
OUT = ROOT / "RESULTS_FULL_METRICS.md"


def metrics_from_csv(csv_path):
    if not csv_path.exists():
        return None
    df = pd.read_csv(csv_path)
    if df.empty or "err_ms" not in df.columns:
        return None
    err = df["err_ms"].abs()
    finite = err[np.isfinite(err)]
    if len(finite) == 0:
        return None
    K = 5
    ok = (err <= 500).values
    lr_k5 = sum(1 for i in range(K-1, len(ok)) if all(ok[i-K+1:i+1])) / max(len(ok)-K+1, 1) * 100
    return {
        "n_beats": int(len(err)),
        "AR@100": round((err <= 100).mean() * 100, 1),
        "AR@500": round((err <= 500).mean() * 100, 1),
        "AR@1000": round((err <= 1000).mean() * 100, 1),
        "MedAE_s": round(float(finite.median()) / 1000, 2),
        "MaxAE_s": round(float(finite.max()) / 1000, 2),
        "MeanAE_s": round(float(finite.mean()) / 1000, 2),
        "LR_K5_%": round(lr_k5, 1),
        "Robust": "✓" if float(finite.median()) / 1000 < 2.0 else "✗",
    }


def collect_all():
    """Walk all trajectory dirs and aggregate per (piece, perf, condition)."""
    rows = []
    sources = [
        ("results/hybrid_full/trajectories", "_dixon_cqt.csv", "Dixon+CQT"),
        ("results/hybrid_full/trajectories", "_hybrid.csv",   "Hybrid v1"),
        ("results/hybrid_v2/trajectories",   "_hybrid_v2.csv", "Hybrid v2"),
        ("results/hybrid_v2/trajectories",   "_dixon_cqt_v2.csv", "Dixon+CQT v2-eval"),
        ("results/confidence_gated_v2/trajectories", "_pass1_v2.csv", "Pass1 rule"),
        ("results/confidence_gated_v2/trajectories", "_pass2_v2.csv", "Pass2 gated"),
        ("results/unified_dixon_v2/trajectories", "_unified_v2.csv", "Unified Dixon v2"),
        ("results/unified_dixon_v2/trajectories", "_dixon_baseline.csv", "Dixon baseline (UD-eval)"),
    ]
    for d, suffix, label in sources:
        path = ROOT / d
        if not path.exists():
            continue
        for f in sorted(path.glob(f"*{suffix}")):
            base = f.name.replace(suffix, "")
            tokens = base.split("_")
            # piece may have underscores; perf is last token
            perf = tokens[-1]
            piece = "_".join(tokens[:-1])
            m = metrics_from_csv(f)
            if m is None:
                continue
            row = {"piece": piece, "perf": perf, "condition": label}
            row.update(m)
            rows.append(row)
    return pd.DataFrame(rows)


def best_of_3_analysis(df):
    """For each (piece, perf), compute best-of-{Pass1, Pass2, Dixon+CQT} selection."""
    if df.empty:
        return pd.DataFrame()
    pivot = df.pivot_table(index=["piece", "perf"], columns="condition",
                            values=["AR@500", "MedAE_s", "MaxAE_s", "LR_K5_%"],
                            aggfunc="first")
    rows = []
    for (piece, perf), sub in pivot.iterrows():
        try:
            ar_p1 = float(sub.get(("AR@500", "Pass1 rule"), np.nan))
            ar_p2 = float(sub.get(("AR@500", "Pass2 gated"), np.nan))
            ar_dx = float(sub.get(("AR@500", "Dixon+CQT"), np.nan))
        except Exception:
            continue
        candidates = {"Pass1": ar_p1, "Pass2": ar_p2, "Dixon+CQT": ar_dx}
        candidates = {k: v for k, v in candidates.items() if not np.isnan(v)}
        if not candidates:
            continue
        best_k = max(candidates, key=candidates.get)
        best_v = candidates[best_k]
        delta_vs_dix = (best_v - ar_dx) if not np.isnan(ar_dx) else np.nan
        rows.append({
            "piece": piece, "perf": perf,
            "AR_Pass1": ar_p1, "AR_Pass2": ar_p2, "AR_Dixon+CQT": ar_dx,
            "best_choice": best_k, "best_AR": best_v,
            "delta_vs_dix": round(delta_vs_dix, 2) if not np.isnan(delta_vs_dix) else "—",
        })
    return pd.DataFrame(rows)


def main():
    df = collect_all()
    print(f"Collected {len(df)} (piece, perf, condition) rows.")
    df.to_csv(ROOT / "results" / "all_trajectories_metrics.csv", index=False)

    parts = [
        f"# Full multi-metric trajectory results",
        "",
        f"_Auto-generated by build_full_metrics_table.py — no metric hidden._",
        f"",
        f"Last updated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"",
        f"Rows: {len(df)} | Pieces: {df['piece'].nunique() if not df.empty else 0} | Conditions: {df['condition'].nunique() if not df.empty else 0}",
        "",
        "## 1. Per-(piece, perf, condition) full metric table",
        "",
        "| Piece | Perf | Condition | AR@100 | AR@500 | AR@1000 | MedAE(s) | MaxAE(s) | MeanAE(s) | LR_K5 | Robust |",
        "|-------|------|-----------|-------:|-------:|--------:|---------:|---------:|----------:|------:|:------:|",
    ]
    for _, r in df.sort_values(["piece", "perf", "condition"]).iterrows():
        parts.append(f"| {r['piece']} | {r['perf']} | {r['condition']} | "
                     f"{r['AR@100']:5.1f} | {r['AR@500']:5.1f} | {r['AR@1000']:5.1f} | "
                     f"{r['MedAE_s']:5.2f} | {r['MaxAE_s']:6.2f} | {r['MeanAE_s']:6.2f} | "
                     f"{r['LR_K5_%']:5.1f} | {r['Robust']} |")

    bo3 = best_of_3_analysis(df)
    if not bo3.empty:
        parts.append("\n## 2. Best-of-3 selection (oracle, requires rehearsal GT)\n")
        parts.append("Per (piece, perf): pick max(AR@500) across {Pass1 rule, Pass2 gated, Dixon+CQT}.")
        parts.append("")
        parts.append("| Piece | Perf | AR_Pass1 | AR_Pass2 | AR_Dixon+CQT | Best | Best AR | Δ vs Dixon |")
        parts.append("|-------|------|---------:|---------:|-------------:|------|--------:|-----------:|")
        for _, r in bo3.sort_values(["piece", "perf"]).iterrows():
            ar_p1 = f"{r['AR_Pass1']:.1f}" if not np.isnan(r['AR_Pass1']) else "—"
            ar_p2 = f"{r['AR_Pass2']:.1f}" if not np.isnan(r['AR_Pass2']) else "—"
            ar_dx = f"{r['AR_Dixon+CQT']:.1f}" if not np.isnan(r['AR_Dixon+CQT']) else "—"
            parts.append(f"| {r['piece']} | {r['perf']} | {ar_p1} | {ar_p2} | {ar_dx} | "
                         f"{r['best_choice']} | {r['best_AR']:.1f} | {r['delta_vs_dix']} |")
        bo3.to_csv(ROOT / "results" / "best_of_3.csv", index=False)
        # Summary
        parts.append("")
        parts.append("**Best-of-3 vs Dixon+CQT summary**")
        deltas = pd.to_numeric(bo3["delta_vs_dix"], errors="coerce")
        valid = deltas.dropna()
        if len(valid):
            n_imp = int((valid > 0.5).sum())
            n_neu = int((valid.abs() <= 0.5).sum())
            n_reg = int((valid < -0.5).sum())
            parts.append(f"- improve (Δ > +0.5pp): {n_imp}/{len(valid)}")
            parts.append(f"- neutral: {n_neu}/{len(valid)}")
            parts.append(f"- **regress (Δ < -0.5pp): {n_reg}/{len(valid)}**")
            parts.append(f"- mean Δ: {valid.mean():+.2f}pp, min Δ: {valid.min():+.2f}pp")
            choice_counts = bo3["best_choice"].value_counts()
            parts.append(f"- best-choice distribution: " +
                         ", ".join(f"{k}={v}" for k, v in choice_counts.items()))

    OUT.write_text("\n".join(parts))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
